### PR TITLE
adding meep

### PR DESCRIPTION
**Pull request by nrichart**

### CODE REVIEW

**Comment by nrichart** [comment]
It fails on hdf5 even though I specified hdf5 to be sure it does not reinstall a new one...

**Review by rmsds — APPROVED** [review]
Looks good, all builds suceeded.

**Comment by rmsds** [comment]
Needs https://github.com/epfl-scitas/spack/pull/255 to be merged beforehand.

**Review by rmsds — CHANGES_REQUESTED** [review]
I think we need to add a default variant for `python` (same as we did for `fftw`) to avoid installing yet another `py-numpy`. (I think `python~tkinter` is not being installed because one already slipped in through the cracks.)

**Comment by nrichart** [comment]
For py-numpy we are in on of this case where the soft depends on blas so we go with `openblas~openmp` but the default numpy is `py-numpy ^openblas+openmp`
For python we will have to define defaults variants per versions I guess

**Review by rmsds — APPROVED** [review]
LGTM

**Pull request merged**
