### PR TITLE
Add external package COMSOL 5.4

### PR DESCRIPTION
**Pull request by rmsds**

### CODE REVIEW

**Review by schlyfts — APPROVED** [review]
Looks harmless enough. I assume that 5.4 will become the default which might confuse some people but maybe in a good way.

**Comment by rmsds** [comment]
@alalazo I would like your take on this one. The tests don't pass, but it seems to me that the "Test PR" workflow doesn't checkout the [spack-repo-externals](https://github.com/epfl-scitas/spack-repo-externals) repository anywhere. Meaning this PR can't really be tested.

**Comment by alalazo** [comment]
This is an issue with our CI pipeline that must be solved for the next release. To check what we need to install we use the production instance of Spack, that doesn't know anything about Comsol 5.4. Hence the error.

**Comment by alalazo** [comment]
Will try to merge it, in case there are issues I'll revert the change.

**Pull request merged**
