### PR TITLE
adding mfem for Picasso's group

### PR DESCRIPTION
**Pull request by nrichart**

### CODE REVIEW

**Comment by rmsds** [comment]
Looks ok in terms of dependencies.
Is there a specific reason why we are going with `@develop` instead of the latest release, 3.4 from May 2018?

**Comment by rmsds** [comment]
Also, is there a reason why we are not compiling it with `%intel` also, all the dependencies seem to be there?

**Review by rmsds — CHANGES_REQUESTED** [review]
See my earlier comments.

**Comment by rmsds** [comment]
> Looks ok in terms of dependencies.
> Is there a specific reason why we are going with `@develop` instead of the latest release, 3.4 from May 2018?

I would actually be for defining a date version tied to a commit and deploy that:
`version('2018-10-17', commit='...')`

**Comment by nrichart** [comment]
For %intel not really, the user asked for gcc. I can try with intel in fact.
I did not check properly upstream they add the version 3.4.0 that as the requirement from the user.

**Pull request closed without merging**
