### PR TITLE
adding py-pytorch

### PR DESCRIPTION
**Pull request by nrichart**

### CODE REVIEW

**Comment by alalazo** [comment]
Wait before merging this, as we don't have yet an automated procedure to activate the packages

**Comment by nrichart** [comment]
Failure is a compilation error with icpc on THD. It gives an internal error on some code that should be valid.

**Comment by alalazo** [comment]
@nrichart I updated the branch as yesterday I added activation of python packages, so we can see if it works correctly also for pytorch.

**Comment by nrichart** [comment]
I rebased the branch to allow the merge and removed the intel version that does not compile for a strange reason

**Review by alalazo — APPROVED** [review]

**Pull request merged**
